### ISSUE TITLE
About SampleRate

### ISSUE THREAD

**Issue by Cagemoney** [JupiterEthan/CRN-causal#2]
Thank you so much for your work, it has benefited me a lot. And I have a question, if I change the sample rate to 32,000, will this affect model performance?

**Comment by JupiterEthan** [comment]
Thanks for your interest in our work. TBH, I have never tried the model on other sampling rates. But that's a great question. If you use the same window size and hop size in milliseconds for 32kHz sampled signals, it would lead to a bigger FFT size and thus widen the LSTM layers. And if you want to keep the overall model size, you might need to reduce the channels in the encoder/decoder. If that is your plan, my prediction is that the performance won't be affected too much.

**Comment by Cagemoney** [comment]
> Thanks for your interest in our work. TBH, I have never tried the model on other sampling rates. But that's a great question. If you use the same window size and hop size in milliseconds for 32kHz sampled signals, it would lead to a bigger FFT size and thus widen the LSTM layers. And if you want to keep the overall model size, you might need to reduce the channels in the encoder/decoder. If that is your plan, my prediction is that the performance won't be affected too much.

**Comment by Cagemoney** [comment]
Thank you for your reply, the facts are as you predicted
